trigger:
  - main

pool:
    vmImage: 'ubuntu-latest'

    steps:
      - task: TerraformInstaller@1
          inputs:
                terraformVersion: 'latest'

      - script: |
            terraform init
                terraform validate
                    terraform plan -out=tfplan
                      displayName: 'Terraform Init, Validate, Plan'

      - script: terraform apply -auto-approve tfplan
          displayName: 'Terraform Apply'

